# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yatessss
email: 897969073@qq.com
description: > # this means to ignore newlines until "baseurl:"
  直到我们失去了,才知道原来拥有的是那么美好.
baseurl:  # the subpath of your site, e.g. /blog
url: "http://www.yatessss.com" # the base hostname & protocol for your site
twitter_username: yatessss
github_username:  yatessss

# Build settings
markdown: kramdown
